import json
from pathlib import Path
from src.config import (
    CHATS_CONV_DIR,
    CHATS_PATH,
    load_settings,
    resolve_logo_to_data_uri,
    logger,
    state
)
from src.utils import get_tokenizer, calculate_message_tokens
from src.history import get_all_history


def resolve_model_provider(model_id: str, settings: dict) -> dict:
    """Resolves the provider id, display name, and logo data for any model ID."""
    model_lower = (model_id or "").lower()
    custom_eps = settings.get("custom_endpoints", [])
    providers = settings.get("providers", [])

    # 1. Check custom endpoints
    for ep in custom_eps:
        ep_name = ep.get("name", "Custom")
        ep_models = ep.get("models", [])
        if isinstance(ep_models, str):
            ep_models = [m.strip() for m in ep_models.split(",") if m.strip()]
        
        # If specific models configured or endpoint name matched in model ID
        if any(m.lower() == model_lower or m.lower() in model_lower for m in ep_models) or f"({ep_name.lower()})" in model_lower:
            logo_uri = resolve_logo_to_data_uri(ep.get("logo", ""))
            return {
                "id": ep_name.lower().replace(" ", "_"),
                "name": ep_name,
                "logo": logo_uri,
                "is_custom": True
            }

    # 2. Check cached state models for explicit custom endpoint assignment
    if state.models:
        for m in state.models.get("data", []):
            if m.get("id") == model_id or m.get("_raw_model_id") == model_id:
                if "_custom_endpoint" in m:
                    ep = m["_custom_endpoint"]
                    ep_name = ep.get("name", "Custom")
                    return {
                        "id": ep_name.lower().replace(" ", "_"),
                        "name": ep_name,
                        "logo": resolve_logo_to_data_uri(ep.get("logo", "")),
                        "is_custom": True
                    }

    # 3. Match against configured providers by keywords
    for p in providers:
        p_id = p.get("id", "other")
        if p_id == "other":
            continue
        keywords = p.get("keywords", [])
        if any(kw.lower() in model_lower for kw in keywords):
            return {
                "id": p_id,
                "name": p.get("name", p_id.capitalize()),
                "logo": resolve_logo_to_data_uri(p.get("logo", "")),
                "is_custom": False
            }

    # 4. Fallback heuristics for common model prefixes
    if "claude" in model_lower or "anthropic" in model_lower:
        return {"id": "anthropic", "name": "Anthropic", "logo": "", "is_custom": False}
    elif "gpt" in model_lower or "o1" in model_lower or "o3" in model_lower or "openai" in model_lower:
        return {"id": "openai", "name": "OpenAI", "logo": "", "is_custom": False}
    elif "gemini" in model_lower or "google" in model_lower:
        return {"id": "google", "name": "Google", "logo": "", "is_custom": False}

    return {"id": "other", "name": "Other", "logo": "", "is_custom": False}


def calculate_turn_tokens(history_messages: list, assistant_msg: dict, encoder) -> tuple[int, int]:
    """Calculates cumulative input tokens (history context up to this turn) and output tokens."""
    # Input tokens = tokens of all preceding messages in context for this generation turn
    input_tokens = 0
    if history_messages:
        for m in history_messages:
            input_tokens += calculate_message_tokens(m, encoder)
        input_tokens += 3  # Assistant reply priming overhead

    # Output tokens = tokens generated by the assistant in this turn
    output_tokens = 0
    content = assistant_msg.get("content", "")
    if isinstance(content, str) and content:
        output_tokens += len(encoder.encode(content))
    elif isinstance(content, list):
        for part in content:
            if isinstance(part, dict) and part.get("text"):
                output_tokens += len(encoder.encode(part["text"]))

    # Include reasoning/thinking tokens in output
    reasoning = assistant_msg.get("reasoning", "")
    if isinstance(reasoning, str) and reasoning.strip():
        output_tokens += len(encoder.encode(reasoning.strip()))

    return input_tokens, output_tokens


def calculate_all_chat_tokens() -> dict:
    """Iterates through all saved conversations, retroactively calculates input and output tokens
    for each model and provider, and returns aggregated totals."""
    import time
    start_time = time.perf_counter()

    settings = load_settings()
    history_data = get_all_history()
    conversations = history_data.get("conversations", [])

    logger.info(f"[Token Counter] Scanning {len(conversations)} conversation(s) from chat logs...")

    by_model = {}
    by_provider = {}
    seen_models = set()
    total_input = 0
    total_output = 0
    total_turns = 0

    # Cache tokenizers to avoid re-instantiating tiktoken encoders per turn
    encoder_cache = {}

    def get_cached_encoder(m_id: str):
        if m_id not in encoder_cache:
            try:
                encoder_cache[m_id] = get_tokenizer(m_id)
            except Exception:
                encoder_cache[m_id] = get_tokenizer("gpt-4o")
        return encoder_cache[m_id]

    for conv in conversations:
        if not isinstance(conv, dict):
            continue
        messages = conv.get("messages", [])
        if not isinstance(messages, list) or not messages:
            continue

        history = []
        for msg in messages:
            if not isinstance(msg, dict):
                continue

            role = msg.get("role")
            if role == "assistant" and not msg.get("isError"):
                model_id = msg.get("model") or "unknown"
                encoder = get_cached_encoder(model_id)

                inp_tokens, out_tokens = calculate_turn_tokens(history, msg, encoder)
                prov_info = resolve_model_provider(model_id, settings)
                prov_id = prov_info["id"]

                if model_id not in seen_models:
                    seen_models.add(model_id)
                    logger.info(f"[Token Counter] Discovered model: '{model_id}' (Provider: {prov_info['name']})")

                # Accumulate per Model
                if model_id not in by_model:
                    by_model[model_id] = {
                        "model_id": model_id,
                        "provider_id": prov_id,
                        "provider_name": prov_info["name"],
                        "provider_logo": prov_info["logo"],
                        "input_tokens": 0,
                        "output_tokens": 0,
                        "total_tokens": 0,
                        "turns": 0
                    }
                by_model[model_id]["input_tokens"] += inp_tokens
                by_model[model_id]["output_tokens"] += out_tokens
                by_model[model_id]["total_tokens"] += (inp_tokens + out_tokens)
                by_model[model_id]["turns"] += 1

                # Accumulate per Provider
                if prov_id not in by_provider:
                    by_provider[prov_id] = {
                        "provider_id": prov_id,
                        "name": prov_info["name"],
                        "logo": prov_info["logo"],
                        "input_tokens": 0,
                        "output_tokens": 0,
                        "total_tokens": 0,
                        "turns": 0,
                        "models": set()
                    }
                by_provider[prov_id]["input_tokens"] += inp_tokens
                by_provider[prov_id]["output_tokens"] += out_tokens
                by_provider[prov_id]["total_tokens"] += (inp_tokens + out_tokens)
                by_provider[prov_id]["turns"] += 1
                by_provider[prov_id]["models"].add(model_id)

                total_input += inp_tokens
                total_output += out_tokens
                total_turns += 1

                # Add assistant response to history so subsequent turns include it
                history.append(msg)
            else:
                history.append(msg)

    # Format providers dictionary and convert sets to counts
    providers_list = []
    for p_id, p_data in by_provider.items():
        providers_list.append({
            "provider_id": p_data["provider_id"],
            "name": p_data["name"],
            "logo": p_data["logo"],
            "input_tokens": p_data["input_tokens"],
            "output_tokens": p_data["output_tokens"],
            "total_tokens": p_data["total_tokens"],
            "turns": p_data["turns"],
            "model_count": len(p_data["models"])
        })
    providers_list.sort(key=lambda x: -x["total_tokens"])

    models_list = list(by_model.values())
    models_list.sort(key=lambda x: -x["total_tokens"])

    elapsed = time.perf_counter() - start_time
    logger.success(
        f"[Token Counter] Tally complete: {total_turns} turn(s), " +
        f"{total_input:,} input tokens, {total_output:,} output tokens " +
        f"across {len(conversations)} conversation(s) ({len(seen_models)} models) in {elapsed:.2f}s"
    )

    return {
        "totals": {
            "input_tokens": total_input,
            "output_tokens": total_output,
            "total_tokens": total_input + total_output,
            "conversations": len(conversations),
            "turns": total_turns
        },
        "by_provider": providers_list,
        "by_model": models_list
    }
